<?php


$products = $this->getBestsellerProducts();

$infinite = $this->getInfinite();
$autoplay = $this->getAutoplay();
$autotime = $this->getAutotime();
$dots = $this->getDots();

?>
<div style="width: 100%">
    <div class="block-title top_title_outer">
        <strong class="top-title">Top Sellers</strong>
    </div>
    <div class="top_sellers">
        <?php foreach ($products as $product): ?>
            <div class="slick-slider-wrapper">
                <div class="topinfo">
                    <div class="prodimage">
                        <a class="product-image item-img" href="<?php echo $product->getProductUrl(); ?>"
                           title="<?php echo $product->getName(); ?>">
                            <?php
                            try {
                                echo $this->helper('catalog/image')->init($product)->resize(150, 84);
                            } catch (Exception $exception) {

                            }
                            ?>
                        </a>
                    </div>
                    <a href="<?php echo $product->getProductUrl(); ?>"
                       title="<?php echo $product->getName(); ?>"><?php echo $product->getName(); ?> </a>
                </div>
                <div class="price_sign">
                    <?php echo $this->getPriceHtml($product); ?>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>

<script type="text/javascript">
    jQuery(document).ready(function () {
        jQuery('.top_sellers').slick({
            infinite: <?php echo $infinite; ?>,
            slidesToShow: 4,
            slidesToScroll: 4,
            autoplay: <?php echo $autoplay; ?>,
            autoplaySpeed: <?php echo $autotime;?>,
            variableWidth: true,
            dots: <?php echo $dots;?>
        });
    });
</script>
